//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogConverter.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_RetailItemGroupLine
    {
        public string ITEMID { get; set; }
        public string GROUPID { get; set; }
        public int BASEITEM { get; set; }
        public decimal QUANT { get; set; }
    }
}
