//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogConverter.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_PublicityScheduleView_ClearanceSale
    {
        public string INVENTLOCATIONID { get; set; }
        public System.DateTime PublicityDate { get; set; }
        public int JournalType { get; set; }
        public string PUBLICITYJOURNALID { get; set; }
        public int ActionType { get; set; }
        public System.DateTime DateBegin { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string ItemId { get; set; }
        public int ValueType { get; set; }
        public decimal Value { get; set; }
        public int ITEMID_CRYSTALL { get; set; }
        public decimal PRICERETAIL { get; set; }
        public Nullable<decimal> PRICEPUBLICITY { get; set; }
        public decimal PROBABLEPRICERETAIL { get; set; }
        public Nullable<decimal> PROBABLEPRICEPUBLICITY { get; set; }
        public decimal QTY { get; set; }
        public int ACTIVE { get; set; }
        public int COUNTDISCTYPE { get; set; }
        public string COMMODITYGROUPID { get; set; }
        public int RuleType { get; set; }
        public string PublicityTransId { get; set; }
        public string TimeBegin { get; set; }
        public string TimeEnd { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedTime { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedTime { get; set; }
    }
}
