//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogConverter.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_PublicityScheduleView
    {
        public string INVENTLOCATIONID { get; set; }
        public System.DateTime PUBLICITYDATE { get; set; }
        public int JOURNALTYPE { get; set; }
        public string PUBLICITYJOURNALID { get; set; }
        public int ACTIONTYPE { get; set; }
        public System.DateTime DATEBEGIN { get; set; }
        public System.DateTime DATEEND { get; set; }
        public string ITEMID { get; set; }
        public int VALUETYPE { get; set; }
        public decimal VALUE { get; set; }
        public int ITEMID_CRYSTALL { get; set; }
        public decimal PRICERETAIL { get; set; }
        public decimal PRICEPUBLICITY { get; set; }
        public decimal PROBABLEPRICERETAIL { get; set; }
        public decimal PROBABLEPRICEPUBLICITY { get; set; }
        public decimal QTY { get; set; }
        public decimal DISCQTY { get; set; }
        public int ACTIVE { get; set; }
        public int COUNTDISCTYPE { get; set; }
        public string COMMODITYGROUPID { get; set; }
        public int RULETYPE { get; set; }
        public string PUBLICITYTRANSID { get; set; }
        public string TimeBegin { get; set; }
        public string TimeEnd { get; set; }
        public System.DateTime MODIFIEDDATE { get; set; }
        public string ModifiedTime { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string CreatedTime { get; set; }
    }
}
