//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogConverter.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_PublicityJournalRefCardType
    {
        public string JOURNALID { get; set; }
        public string DISCCARDTYPEID { get; set; }
    }
}
