//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogConverter.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_InventItemRange
    {
        public string RANGEID { get; set; }
        public string RANGEIDPARENT { get; set; }
        public string PREFIX { get; set; }
        public string NAMEALIAS { get; set; }
        public int ITEMRANGEID_CRYSTALL { get; set; }
        public Nullable<long> RANGELEVEL { get; set; }
    }
}
