//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogConverter.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DAX2012_PreProdEntities : DbContext
    {
        public DAX2012_PreProdEntities()
            : base("name=DAX2012_PreProdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CRM_BrandHolderTable> CRM_BrandHolderTable { get; set; }
        public virtual DbSet<CRM_BrandTable> CRM_BrandTable { get; set; }
        public virtual DbSet<CRM_InventDimCombination> CRM_InventDimCombination { get; set; }
        public virtual DbSet<CRM_InventItemRange> CRM_InventItemRange { get; set; }
        public virtual DbSet<CRM_InventSalesDepartment> CRM_InventSalesDepartment { get; set; }
        public virtual DbSet<CRM_InventTable> CRM_InventTable { get; set; }
        public virtual DbSet<CRM_PublicityJournalRefCardType> CRM_PublicityJournalRefCardType { get; set; }
        public virtual DbSet<CRM_PublicityScheduleView> CRM_PublicityScheduleView { get; set; }
        public virtual DbSet<CRM_PublicityScheduleView_ClearanceSale> CRM_PublicityScheduleView_ClearanceSale { get; set; }
        public virtual DbSet<CRM_RetailItemGroup> CRM_RetailItemGroup { get; set; }
        public virtual DbSet<CRM_RetailItemGroupLine> CRM_RetailItemGroupLine { get; set; }
    }
}
